"""Agregadno llave foranea de client 2  a la tabla properties_client

Revision ID: 4b5a630021e3
Revises: 
Create Date: 2023-03-28 17:20:09.529545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b5a630021e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties_client')
    # ### end Alembic commands ###


def downgrade() -> None:
    
    op.create_table('properties_client',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.Column('status_range', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('type_properties_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_properties_id'], ['type_properties.id'], name='properties_client_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
