"""corregir backref 2 

Revision ID: 4d30f1869aa7
Revises: 368302722e6b
Create Date: 2023-03-31 09:32:19.544601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d30f1869aa7'
down_revision = '368302722e6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('references_client')
    op.drop_table('propertie_client')
    op.drop_table('client')
    op.drop_table('user')
    op.drop_table('type_properties')

    # ### end Alembic commands ###


def downgrade() -> None:
   
    op.create_table('type_properties',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('type_user', mysql.ENUM('staf', 'user'), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('client',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type_document', mysql.ENUM('CC', 'NIT', 'TI', 'PS', 'EXT'), nullable=False),
    sa.Column('num_document', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('document_from', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('expedition_date_document', sa.DATE(), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('birth_city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sex', mysql.ENUM('MASCULINO', 'FEMENINO', 'OTRO'), nullable=True),
    sa.Column('telephone_number_1', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('telephone_number_2', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city_residence', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('civil_status', mysql.ENUM('SOLTERO', 'CASADO', 'U LIBRE'), nullable=True),
    sa.Column('address_1', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address_2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('profession', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fixed_income_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('other_income', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('approved_credit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status_credit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('maximum_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('minimum_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('risk_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('habit_pay', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debt_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fixed_expenses', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('data_credit_point', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_bank', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type_account_bank', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('observation', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id_user_create', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='client_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='client_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    op.create_table('propertie_client',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.Column('status_range', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('type_properties_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='propertie_client_ibfk_2'),
    sa.ForeignKeyConstraint(['type_properties_id'], ['type_properties.id'], name='propertie_client_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('references_client',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('frist_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('telephone_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('type_reference', mysql.ENUM('PERSONAL', 'FAMILIAR', 'LABORAL'), nullable=True),
    sa.Column('relation', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='references_client_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
